Email confirmation Functionality
irtazazulfiqar/CF-DjangoTask pull request #4
Opened 2024-08-07 11:03 UTC by irtazazulfiqar

2024-08-08 12:59 UTC, m-shayan-ahmad requested changes

2024-08-08 12:59 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/apps.py
> +
No extra line spaces.

2024-08-08 12:59 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/models/borrowed_book.py
> +        super().save(*args, **kwargs)
There should be a single source of truth, and that is where we are adding the borrowed book. Also, this limit should be customizable via env. Default should be 1 week.

2024-08-08 12:59 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/signals.py
> +        """
Create a HTML template for this email.

2024-08-08 12:59 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/signals.py
> +        sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
```suggestion
        sendgrid = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
```

2024-08-08 12:59 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/signals.py
> +        print(response.headers)
No print statements.

2024-08-09 09:00 UTC, irtazazulfiqar commented on mydemoproject/demoapp1/signals.py
> +        """
catered in next PR

2024-08-12 11:54 UTC, m-shayan-ahmad approved these changes
There are some changes that must be taken care of in next PR.

2024-08-12 11:54 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/models/borrowed_book.py
> +                os.getenv('EMAIL_DAYS')))
Create .env.example file.

2024-08-12 11:54 UTC, m-shayan-ahmad commented on mydemoproject/demoapp1/models/borrowed_book.py
> +                os.getenv('EMAIL_DAYS')))
Also, indent the parentheses correctly.

2024-08-12 11:54 UTC, merged